// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: gateway.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_proto protoreflect.FileDescriptor

var file_gateway_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x32, 0x47, 0x0a, 0x0f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x34, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x4d, 0x73, 0x67, 0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var file_gateway_proto_goTypes = []interface{}{
	(*ReqMsg)(nil), // 0: message.ReqMsg
	(*ResMsg)(nil), // 1: message.ResMsg
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: message.GatewayProtocol.RequestService:input_type -> message.ReqMsg
	1, // 1: message.GatewayProtocol.RequestService:output_type -> message.ResMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_rawDesc = nil
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GatewayProtocolClient is the client API for GatewayProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayProtocolClient interface {
	RequestService(ctx context.Context, in *ReqMsg, opts ...grpc.CallOption) (*ResMsg, error)
}

type gatewayProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayProtocolClient(cc grpc.ClientConnInterface) GatewayProtocolClient {
	return &gatewayProtocolClient{cc}
}

func (c *gatewayProtocolClient) RequestService(ctx context.Context, in *ReqMsg, opts ...grpc.CallOption) (*ResMsg, error) {
	out := new(ResMsg)
	err := c.cc.Invoke(ctx, "/message.GatewayProtocol/RequestService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayProtocolServer is the server API for GatewayProtocol service.
type GatewayProtocolServer interface {
	RequestService(context.Context, *ReqMsg) (*ResMsg, error)
}

// UnimplementedGatewayProtocolServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayProtocolServer struct {
}

func (*UnimplementedGatewayProtocolServer) RequestService(context.Context, *ReqMsg) (*ResMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestService not implemented")
}

func RegisterGatewayProtocolServer(s *grpc.Server, srv GatewayProtocolServer) {
	s.RegisterService(&_GatewayProtocol_serviceDesc, srv)
}

func _GatewayProtocol_RequestService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayProtocolServer).RequestService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.GatewayProtocol/RequestService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayProtocolServer).RequestService(ctx, req.(*ReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayProtocol_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.GatewayProtocol",
	HandlerType: (*GatewayProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestService",
			Handler:    _GatewayProtocol_RequestService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
